export const ERROR_CODES = Object.freeze({
  USAGE_ERROR: 'USAGE_ERROR',
  AUTH_MISSING: 'AUTH_MISSING',
  MODEL_UNSUPPORTED: 'MODEL_UNSUPPORTED',
  PROVIDER_HTTP_ERROR: 'PROVIDER_HTTP_ERROR',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_RESPONSE_INVALID: 'PROVIDER_RESPONSE_INVALID',
  TOOL_ARGUMENT_INVALID: 'TOOL_ARGUMENT_INVALID',
  TOOL_APPROVAL_REQUIRED: 'TOOL_APPROVAL_REQUIRED',
  TOOL_DENIED: 'TOOL_DENIED',
  PATH_OUTSIDE_WORKSPACE: 'PATH_OUTSIDE_WORKSPACE',
  COMMAND_TIMEOUT: 'COMMAND_TIMEOUT',
  COMMAND_CANCELLED: 'COMMAND_CANCELLED',
  DUPLICATE_TOOL_LOOP: 'DUPLICATE_TOOL_LOOP',
  STEP_LIMIT: 'STEP_LIMIT',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_PROJECT_MISMATCH: 'SESSION_PROJECT_MISMATCH',
  SESSION_CORRUPT: 'SESSION_CORRUPT',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED'
});

const EXIT_CODES = Object.freeze({
  USAGE_ERROR: 2,
  AUTH_MISSING: 10,
  MODEL_UNSUPPORTED: 11,
  PROVIDER_HTTP_ERROR: 12,
  PROVIDER_TIMEOUT: 13,
  PROVIDER_RESPONSE_INVALID: 14,
  TOOL_ARGUMENT_INVALID: 20,
  TOOL_APPROVAL_REQUIRED: 21,
  TOOL_DENIED: 22,
  PATH_OUTSIDE_WORKSPACE: 23,
  COMMAND_TIMEOUT: 24,
  COMMAND_CANCELLED: 130,
  DUPLICATE_TOOL_LOOP: 30,
  STEP_LIMIT: 31,
  SESSION_NOT_FOUND: 40,
  SESSION_PROJECT_MISMATCH: 41,
  SESSION_CORRUPT: 42,
  VERIFICATION_FAILED: 50
});

export class CorezError extends Error {
  constructor(code, message, details = {}, options = {}) {
    super(message, options);
    this.name = 'CorezError';
    this.code = code;
    this.details = details;
  }
}

export function exitCodeForError(error) {
  return EXIT_CODES[error?.code] || 1;
}
