/**
 * CoreZ Reflection & Repair Engine
 *
 * Provides a bounded, deterministic reflection-and-repair loop:
 *   1. Evaluates generated responses against intent contracts and output format requirements.
 *   2. Identifies explicit requirement gaps or forbidden contract violations.
 *   3. Executes targeted, deterministic local repairs without altering usage limits,
 *      making extra uncontrolled API calls, or modifying pricing.
 *   4. Logs lightweight anonymous quality metrics for observability.
 */

export const MAX_REPAIR_ATTEMPTS = 1;
const _qualityMetricsLog = [];

/**
 * Evaluate generated response content against the request intent contract and format expectations.
 *
 * @param {string} responseContent — text generated by AI model
 * @param {object} contract — intent contract containing mustAchieve, mustPreserve, mustNotChange
 * @param {object} intent — fine-grained intent object
 * @returns {object} evaluation result: { isCompliant, score, violations, missingRequirements }
 */
export function evaluateResponse(responseContent, contract = {}, intent = {}) {
  const text = typeof responseContent === 'string' ? responseContent.trim() : '';
  const violations = [];
  const missingRequirements = [];

  if (!text) {
    return {
      isCompliant: false,
      score: 0,
      violations: ['Empty response generated by AI provider'],
      missingRequirements: ['Response content'],
    };
  }

  const lower = text.toLowerCase();

  // 1. Evaluate explicit mustAchieve requirements
  const mustAchieve = Array.isArray(contract?.mustAchieve) ? contract.mustAchieve : [];
  for (const req of mustAchieve) {
    if (typeof req !== 'string') continue;
    const reqLower = req.toLowerCase();
    // Key signal check
    if (reqLower.includes('fix') && reqLower.includes('bug') && !lower.includes('fix') && !lower.includes('cause') && !lower.includes('issue')) {
      missingRequirements.push(`Missing bug fix explanation for: ${req}`);
    }
  }

  // 2. Evaluate mustNotChange / forbidden rules
  const mustNotChange = [
    ...(Array.isArray(contract?.mustNotChange) ? contract.mustNotChange : []),
    ...(Array.isArray(contract?.mustPreserve) ? contract.mustPreserve : []),
  ];

  for (const rule of mustNotChange) {
    if (typeof rule !== 'string') continue;
    const ruleLower = rule.toLowerCase();

    // Guard against modifying usage, rate, token, billing, or provider limits
    if (ruleLower.includes('usage') || ruleLower.includes('rate limit') || ruleLower.includes('token limit') || ruleLower.includes('billing')) {
      if (/\b(usage\s*limit|rate\s*limit|token\s*limit|monthly\s*quota|tier\s*override|usage_limit|rate_limit|token_limit|monthly_quota|tier_override)\b[^=;\n]{0,20}\s*=\s*/i.test(text)) {
        violations.push(`Violation of forbidden change rule: ${rule}`);
      }
    }
  }

  // 3. Evaluate Output Format Compliance
  const expectedFormat = intent?.outputFormat || 'text';
  if (expectedFormat === 'jsx') {
    const hasCodeBlock = text.includes('```jsx') || text.includes('```tsx') || text.includes('```react') || text.includes('export default');
    const jsxRequested = ['website_creation', 'game_creation', 'design_task'].includes(intent?.type)
      || ['website_creation', 'game_creation', 'design_task'].includes(intent?.primaryIntent)
      || intent?.type === 'app';
    if (!hasCodeBlock && jsxRequested) {
      violations.push('Expected React/JSX code output block but none was provided');
    }
  } else if (expectedFormat === 'html') {
    const hasHtmlBlock = text.includes('```html') || text.includes('<html') || text.includes('<!DOCTYPE');
    if (!hasHtmlBlock) {
      violations.push('Expected HTML code block but none was provided');
    }
  }

  const isCompliant = violations.length === 0 && missingRequirements.length === 0;
  const score = isCompliant ? 10 : Math.max(1, 10 - (violations.length * 3 + missingRequirements.length * 2));

  return {
    isCompliant,
    score,
    violations,
    missingRequirements,
  };
}

/**
 * Bounded repair loop: performs deterministic local repairs when material issues are found.
 * Stops strictly after maxAttempts (default: 1).
 *
 * @param {string} responseContent
 * @param {object} evaluationResult
 * @param {object} contract
 * @param {number} [maxAttempts=1]
 * @param {number} [currentAttempt=0]
 * @returns {object} { finalContent, repaired, attempts, evaluation }
 */
export function repairResponse(
  responseContent,
  evaluationResult,
  contract = {},
  maxAttempts = MAX_REPAIR_ATTEMPTS,
  currentAttempt = 0,
  intent = {}
) {
  if (evaluationResult.isCompliant || currentAttempt >= maxAttempts) {
    return {
      finalContent: responseContent,
      repaired: false,
      attempts: currentAttempt,
      evaluation: evaluationResult,
    };
  }

  let repairedContent = responseContent;

  // Apply deterministic local repairs for detected violations
  for (const violation of evaluationResult.violations) {
    // Repair unclosed code block if truncated
    if (violation.includes('code output block') && !repairedContent.includes('```')) {
      repairedContent += '\n\n```jsx\n// Self-contained component fallback\nexport default function App() {\n  return <div className="p-4">App Content</div>;\n}\n```';
    }
    // Revert forbidden usage/rate limit mutations if accidentally introduced
    if (violation.includes('usage') || violation.includes('rate_limit')) {
      repairedContent = repairedContent.replace(/\b(usage_limit|rate_limit|token_limit|monthly_quota)\s*=\s*[^;\n]+/gi, '');
    }
  }

  const newEval = evaluateResponse(repairedContent, contract, intent);

  return {
    finalContent: repairedContent,
    repaired: true,
    attempts: currentAttempt + 1,
    evaluation: newEval,
  };
}

/**
 * Record lightweight, anonymous quality signals for observability.
 *
 * @param {object} signal
 */
export function recordQualitySignal(signal = {}) {
  const metric = {
    timestamp: Date.now(),
    intentType: signal.intentType || 'unknown',
    confidence: signal.confidence || 0,
    selectedSkillsCount: signal.selectedSkillsCount || 0,
    isCompliant: signal.isCompliant !== false,
    violationsCount: signal.violationsCount || 0,
    repaired: Boolean(signal.repaired),
  };

  _qualityMetricsLog.push(metric);
  if (_qualityMetricsLog.length > 200) {
    _qualityMetricsLog.shift();
  }
}

/**
 * Retrieve current in-memory quality metrics log.
 */
export function getQualityMetrics() {
  return [..._qualityMetricsLog];
}
