/**
 * CoreZ Reflection & Repair Engine
 *
 * Provides a bounded, deterministic reflection-and-repair loop:
 *   1. Evaluates generated responses against intent contracts and output format requirements.
 *   2. Identifies explicit requirement gaps or forbidden contract violations.
 *   3. Executes targeted, deterministic local repairs without altering usage limits,
 *      making extra uncontrolled API calls, or modifying pricing.
 *   4. Logs lightweight anonymous quality metrics for observability.
 */

const _qualityMetricsLog = [];

/**
 * Evaluate generated response content against the request intent contract and format expectations.
 *
 * @param {string} responseContent — text generated by AI model
 * @param {object} contract — intent contract containing mustAchieve, mustPreserve, mustNotChange
 * @param {object} intent — fine-grained intent object
 * @returns {object} evaluation result: { isCompliant, score, violations, missingRequirements }
 */
export function evaluateResponse(responseContent, contract = {}, intent = {}) {
  const text =
    typeof responseContent === "string" ? responseContent.trim() : "";
  const violations = [];
  const missingRequirements = [];

  if (!text) {
    return {
      isCompliant: false,
      score: 0,
      violations: ["Empty response generated by AI provider"],
      missingRequirements: ["Response content"],
    };
  }

  const lower = text.toLowerCase();

  // 1. Evaluate explicit mustAchieve requirements
  const mustAchieve = Array.isArray(contract?.mustAchieve)
    ? contract.mustAchieve
    : [];
  for (const req of mustAchieve) {
    if (typeof req !== "string") continue;
    const reqLower = req.toLowerCase();
    // Key signal check
    if (
      reqLower.includes("fix") &&
      reqLower.includes("bug") &&
      !lower.includes("fix") &&
      !lower.includes("cause") &&
      !lower.includes("issue")
    ) {
      missingRequirements.push(`Missing bug fix explanation for: ${req}`);
    }
  }

  // 2. Evaluate mustNotChange / forbidden rules
  const mustNotChange = [
    ...(Array.isArray(contract?.mustNotChange) ? contract.mustNotChange : []),
    ...(Array.isArray(contract?.mustPreserve) ? contract.mustPreserve : []),
  ];

  for (const rule of mustNotChange) {
    if (typeof rule !== "string") continue;
    const ruleLower = rule.toLowerCase();

    // Guard against modifying usage, rate, token, billing, or provider limits
    if (
      ruleLower.includes("usage") ||
      ruleLower.includes("rate limit") ||
      ruleLower.includes("token limit") ||
      ruleLower.includes("billing")
    ) {
      if (
        /\b(usage\s*limit|rate\s*limit|token\s*limit|monthly\s*quota|tier\s*override|usage_limit|rate_limit|token_limit|monthly_quota|tier_override)\b[^=;\n]{0,20}\s*=\s*/i.test(
          text,
        )
      ) {
        violations.push(`Violation of forbidden change rule: ${rule}`);
      }
    }
  }

  // 3. Evaluate Output Format Compliance
  const expectedFormat = intent?.outputFormat || "text";
  if (expectedFormat === "jsx") {
    const hasCodeBlock =
      text.includes("```jsx") ||
      text.includes("```tsx") ||
      text.includes("```react") ||
      text.includes("export default");
    const jsxRequested =
      ["website_creation", "game_creation", "design_task"].includes(
        intent?.type,
      ) ||
      ["website_creation", "game_creation", "design_task"].includes(
        intent?.primaryIntent,
      ) ||
      intent?.type === "app";
    if (!hasCodeBlock && jsxRequested) {
      violations.push(
        "Expected React/JSX code output block but none was provided",
      );
    }
  } else if (expectedFormat === "html") {
    const hasHtmlBlock =
      text.includes("```html") ||
      text.includes("<html") ||
      text.includes("<!DOCTYPE");
    if (!hasHtmlBlock) {
      violations.push("Expected HTML code block but none was provided");
    } else if (
      (intent?.type === "game_creation" ||
        intent?.primaryIntent === "game_creation") &&
      !hasGameChatBrief(text)
    ) {
      violations.push("Missing short game brief before code block");
      missingRequirements.push(
        "Game chat brief (1-2 sentences: title, goal, controls)",
      );
    }
  } else if (
    (intent?.type === "game_creation" ||
      intent?.primaryIntent === "game_creation") &&
    (text.includes("```html") ||
      text.includes("<html") ||
      text.includes("<!DOCTYPE")) &&
    !hasGameChatBrief(text)
  ) {
    violations.push("Missing short game brief before code block");
    missingRequirements.push(
      "Game chat brief (1-2 sentences: title, goal, controls)",
    );
  }

  const isCompliant =
    violations.length === 0 && missingRequirements.length === 0;
  const score = isCompliant
    ? 10
    : Math.max(
        1,
        10 - (violations.length * 3 + missingRequirements.length * 2),
      );

  return {
    isCompliant,
    score,
    violations,
    missingRequirements,
  };
}

/**
 * Deterministic client-side fallback: every game deliverable must reach chat
 * with a 1-2 sentence brief BEFORE the code block. Mirrors the worker's
 * ensureGameChatBrief so code-only model output still gets a description.
 * Non-game answers pass through unchanged.
 */
export function ensureGameChatBrief(content) {
  const text = String(content || "");
  if (!text.trim()) return text;
  const fenceIdx = text.search(/```/);
  const htmlIdx = text.search(/(?:<!DOCTYPE\s+html|<html[\s>])/i);
  if (fenceIdx === -1 && htmlIdx === -1) return text;
  const codeStart = fenceIdx !== -1 ? fenceIdx : htmlIdx;
  const code = text.slice(codeStart);
  const hasLoop = /requestAnimationFrame|getContext\s*\(/i.test(code);
  const hasControls = /keydown|keyup|touchstart|touchend|pointerdown/i.test(code);
  if (!hasLoop || !hasControls) return text;
  const gameLike =
    /\b(score|collision|collide|overlap)\b/i.test(code) ||
    /\b(game|player|enemy|level|win\b|lose\b)/i.test(code.slice(0, 2000));
  if (!gameLike) return text;

  const rawPreamble = codeStart > 0 ? text.slice(0, codeStart).trim() : "";
  const preamble = rawPreamble
    .replace(/(?:\r?\n|^)\s*(?:Fullscreen|Preview)\s*$/i, "")
    .trim();
  if (preamble.length >= 20 && /[a-zA-Z]{3,}/.test(preamble)) return text;

  const titleMatch =
    code.match(/<title>([^<]{3,80})<\/title>/i) ||
    code.match(/<h1[^>]*>([^<]{3,60})</i);
  let title = (titleMatch && titleMatch[1].trim()) || "Your new game";
  title = title.replace(/\s+/g, " ").slice(0, 60);

  let goal = "play to win";
  if (/collect|coin|orb/i.test(code)) goal = "collect to score and win";
  else if (/score/i.test(code)) goal = "score points to win";
  else if (/surviv|dodge|avoid|enemy/i.test(code))
    goal = "dodge enemies and survive";

  const controls = [];
  if (/KeyW|WASD/i.test(code)) controls.push("Move with WASD/Arrow keys");
  else if (/ArrowLeft|keydown/i.test(code))
    controls.push("Move with the Arrow keys");
  if (/Space/i.test(code)) controls.push("Space to jump/launch");
  if (/touchstart|touchend|pointerdown/i.test(code))
    controls.push("plus on-screen touch controls");
  if (controls.length === 0) controls.push("Use the keyboard to play");

  return `Here's **${title}** — ${goal}. ${controls.join(", ")}.\n\n${text.trimStart()}`;
}

/**
 * True when a game_creation response carries a usable chat brief before code.
 */
export function hasGameChatBrief(content) {
  const text = String(content || "");
  const fenceIdx = text.search(/```/);
  const htmlIdx = text.search(/(?:<!DOCTYPE\s+html|<html[\s>])/i);
  if (fenceIdx === -1 && htmlIdx === -1) return false;
  const start = fenceIdx !== -1 ? fenceIdx : htmlIdx;
  const preamble = (start > 0 ? text.slice(0, start).trim() : "")
    .replace(/(?:\r?\n|^)\s*(?:Fullscreen|Preview)\s*$/i, "")
    .trim();
  return preamble.length >= 20 && /[a-zA-Z]{3,}/.test(preamble);
}

/**
 * Progress-aware repair loop: performs deterministic local repairs when
 * material issues are found and iterates while each pass makes a measurable
 * change to the content. It stops when the response is compliant, when a
 * pass changes nothing (genuinely blocked), or when an explicit caller
 * ceiling is reached. There is no fixed default attempt cap.
 *
 * @param {string} responseContent
 * @param {object} evaluationResult
 * @param {object} contract
 * @param {number} [maxAttempts=Infinity]
 * @param {number} [currentAttempt=0]
 * @returns {object} { finalContent, repaired, attempts, evaluation }
 */
export function repairResponse(
  responseContent,
  evaluationResult,
  contract = {},
  maxAttempts = Number.MAX_SAFE_INTEGER,
  currentAttempt = 0,
  intent = {},
) {
  let content = responseContent;
  let evaluation = evaluationResult;
  let attempt = currentAttempt;

  while (!evaluation.isCompliant && attempt < maxAttempts) {
    const before = content;

    // Apply deterministic local repairs for detected violations
    for (const violation of evaluation.violations) {
      if (
        violation.includes("Missing short game brief") &&
        !hasGameChatBrief(content)
      ) {
        content = ensureGameChatBrief(content);
      }
      if (violation.includes("code output block") && !content.includes("```")) {
        content +=
          '\n\n```jsx\n// Self-contained component fallback\nexport default function App() {\n  return <div className="p-4">App Content</div>;\n}\n```';
      }
      if (violation.includes("usage") || violation.includes("rate_limit")) {
        content = content.replace(
          /\b(usage_limit|rate_limit|token_limit|monthly_quota)\s*=\s*[^;\n]+/gi,
          "",
        );
      }
    }

    attempt += 1;

    // Progress guard: if a full pass changed nothing, the response is
    // genuinely blocked and further identical attempts cannot help.
    if (content === before) {
      return {
        finalContent: content,
        repaired: attempt > currentAttempt,
        attempts: attempt,
        evaluation,
      };
    }

    evaluation = evaluateResponse(content, contract, intent);
  }

  return {
    finalContent: content,
    repaired: attempt > currentAttempt,
    attempts: attempt,
    evaluation,
  };
}

/**
 * Record lightweight, anonymous quality signals for observability.
 *
 * @param {object} signal
 */
export function recordQualitySignal(signal = {}) {
  const metric = {
    timestamp: Date.now(),
    intentType: signal.intentType || "unknown",
    confidence: signal.confidence || 0,
    selectedSkillsCount: signal.selectedSkillsCount || 0,
    isCompliant: signal.isCompliant !== false,
    violationsCount: signal.violationsCount || 0,
    repaired: Boolean(signal.repaired),
  };

  _qualityMetricsLog.push(metric);
  if (_qualityMetricsLog.length > 200) {
    _qualityMetricsLog.shift();
  }
}

/**
 * Retrieve current in-memory quality metrics log.
 */
export function getQualityMetrics() {
  return [..._qualityMetricsLog];
}
