/**
 * CoreZ Superpowers Skill Definitions
 * Standardized metadata definitions for Superpowers methodology skills and CoreZ specialist capabilities.
 * Source reference: obra/superpowers (MIT License)
 */

export const SUPERPOWERS_SKILLS = [
  {
    id: "using-superpowers",
    name: "Using Superpowers",
    description:
      "Bootstrap & workflow engine entry point for engineering and application building.",
    triggers: ["build", "develop", "debug", "create", "fix", "refactor"],
    phase: "BOOTSTRAP",
    priority: 1,
    dependencies: [],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `Before answering or writing code for complex engineering tasks, analyze the intent, determine task type, resolve applicable skills, construct the workflow state machine, and execute each stage systematically.`,
  },
  {
    id: "brainstorming",
    name: "Brainstorming & Specification",
    description:
      "Socratic design refinement, requirements discovery, and specification formulation before coding.",
    triggers: [
      "new app",
      "build me",
      "dashboard",
      "saas",
      "game",
      "prototype",
      "design",
    ],
    phase: "BRAINSTORMING",
    priority: 10,
    dependencies: [],
    compatibleIntents: ["app"],
    requiresTools: [],
    instructions: `Step back before writing code. Clarify user objectives, outline visual and architectural design, explore trade-offs, and produce a clear, validated specification chunk by chunk.`,
  },
  {
    id: "writing-plans",
    name: "Writing Implementation Plans",
    description:
      "Decomposes approved specifications into granular, bite-sized tasks with exact file paths, expected outputs, and verification criteria.",
    triggers: ["plan", "architecture", "decompose", "roadmap", "spec ready"],
    phase: "PLANNING",
    priority: 20,
    dependencies: ["brainstorming"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `Break engineering work into granular tasks (2-5 minutes each). Specify target files, exact code requirements, verification steps, and dependency relationships (DAG format).`,
  },
  {
    id: "subagent-driven-development",
    name: "Subagent Driven Development",
    description:
      "Dispatches fresh subagents per task brief with isolated context and two-stage review gates.",
    triggers: [
      "multi-agent",
      "subagents",
      "parallel execution",
      "large request",
    ],
    phase: "IMPLEMENTING",
    priority: 30,
    dependencies: ["writing-plans"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `Dispatch isolated subagent execution calls using task briefs containing goal, constraints, relevant files, and verification goals. Avoid context contamination.`,
  },
  {
    id: "executing-plans",
    name: "Executing Plans",
    description:
      "Sequential or batched execution of implementation plan tasks with progress tracking and state updates.",
    triggers: ["execute plan", "run tasks", "build features"],
    phase: "IMPLEMENTING",
    priority: 31,
    dependencies: ["writing-plans"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `Execute plan tasks in DAG order. Track completion status in real-time, enforcing RED-GREEN-REFACTOR for each engineering task.`,
  },
  {
    id: "dispatching-parallel-agents",
    name: "Dispatching Parallel Agents",
    description:
      "Concurrently executes non-overlapping independent tasks across specialist agents.",
    triggers: ["parallel", "concurrent", "independent tasks"],
    phase: "IMPLEMENTING",
    priority: 35,
    dependencies: ["subagent-driven-development"],
    compatibleIntents: ["app"],
    requiresTools: [],
    instructions: `Identify independent DAG nodes with no shared resource locks and dispatch them concurrently. Sequence dependent nodes.`,
  },
  {
    id: "systematic-debugging",
    name: "Systematic Debugging",
    description:
      "Disciplined 7-phase root-cause investigation process for bug reports and runtime failures.",
    triggers: [
      "bug",
      "crash",
      "error",
      "fails",
      "exception",
      "stack trace",
      "not working",
    ],
    phase: "IMPLEMENTING",
    priority: 15,
    dependencies: [],
    compatibleIntents: ["code-help"],
    requiresTools: [],
    instructions: `Follow 7-phase root cause process: 1. Root-cause investigation, 2. Pattern analysis, 3. Hypothesis, 4. Test, 5. Minimal fix, 6. Regression test, 7. Verification. Do not guess fixes randomly.`,
  },
  {
    id: "test-driven-development",
    name: "Test-Driven Development (TDD)",
    description:
      "Enforces strict RED-GREEN-REFACTOR cycle: failing test first, minimal implementation, passing test, refactor.",
    triggers: ["tdd", "unit test", "failing test", "implement feature"],
    phase: "IMPLEMENTING",
    priority: 40,
    dependencies: ["writing-plans"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `Write failing test (RED), verify failure, write minimal code to satisfy test (GREEN), verify test passes, refactor code while keeping tests green.`,
  },
  {
    id: "requesting-code-review",
    name: "Requesting Code Review",
    description:
      "Runs two-stage review gate: specification compliance review and code-quality review.",
    triggers: ["review code", "review gate", "code quality", "spec check"],
    phase: "REVIEWING",
    priority: 50,
    dependencies: ["test-driven-development"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `Evaluate implementation output against specification and code quality criteria (security, performance, maintainability, accessibility). Send critical issues to REPAIRING.`,
  },
  {
    id: "receiving-code-review",
    name: "Receiving Code Review",
    description:
      "Processes review feedback and executes minimal targeted repairs for critical findings.",
    triggers: ["repair", "fix review finding", "review feedback"],
    phase: "REPAIRING",
    priority: 55,
    dependencies: ["requesting-code-review"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `Address critical review findings with minimal corrective edits, re-run tests, and return to review gate.`,
  },
  {
    id: "verification-before-completion",
    name: "Verification Before Completion",
    description:
      "Mandatory gate requiring empirical evidence records (tests, exit codes, builds) before claiming completion.",
    triggers: ["verify completion", "evidence gate", "completion check"],
    phase: "VERIFYING",
    priority: 60,
    dependencies: ["requesting-code-review"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: [],
    instructions: `No completion claim without empirical verification evidence records (command, exit code, test pass/fail counts). Explicitly report if tools were unavailable.`,
  },
  {
    id: "finishing-a-development-branch",
    name: "Finishing a Development Branch",
    description:
      "Final verification, clean up, and completion decision for verified development tasks.",
    triggers: ["finish branch", "complete task", "ship feature"],
    phase: "COMPLETE",
    priority: 70,
    dependencies: ["verification-before-completion"],
    compatibleIntents: ["app", "code-help"],
    requiresTools: ["git"],
    instructions: `Verify branch cleanliness, confirm pass baseline, summarize verification evidence, and finalize task deliverable.`,
  },
];

export const COREZ_SPECIALIST_SKILLS = [
  {
    id: "frontend-modern-design",
    name: "Frontend Modern Design",
    description:
      "High-aesthetic UI creation using modern typography, dark mode, HSL color palettes, and glassmorphism.",
    triggers: ["ui", "modern design", "css", "landing page", "dashboard ui"],
    phase: "IMPLEMENTING",
    priority: 25,
    dependencies: [],
    compatibleIntents: ["app"],
    requiresTools: [],
    instructions:
      "Create responsive, visually stunning web UI with dark modes, curated HSL color palettes, modern typography, and smooth CSS micro-interactions. Establish the visual direction (palette, type scale, spacing rhythm) before writing markup, then implement with strict z-index layering and explicit container positioning.",
  },
  {
    id: "game-development",
    name: "Game Development",
    description:
      "2D/3D web games, HTML5 Canvas engines, physics simulators, and word game dictionaries.",
    triggers: [
      "game",
      "canvas game",
      "arcade",
      "snake",
      "pong",
      "wordle",
      "scrabble",
    ],
    phase: "IMPLEMENTING",
    priority: 25,
    dependencies: [],
    compatibleIntents: ["app"],
    requiresTools: [],
    instructions:
      "Build runnable single-file HTML5 canvas games with complete game loops, input management, collision detection, and asset integration. Structure the code around a fixed-timestep loop, keep entity state in refs, and always include scoring, controls, and a restartable game-over state.",
  },
  {
    id: "visual-creative",
    name: "Visual Creative Engine",
    description:
      "Provider-neutral image generation, visual asset manifests, and coherent layout direction.",
    triggers: ["image", "art", "background", "sprite", "visual asset"],
    phase: "IMPLEMENTING",
    priority: 22,
    dependencies: [],
    compatibleIntents: ["app"],
    requiresTools: [],
    instructions:
      "Formulate structured JSON asset manifests for visual requirements and invoke the configured image-generation pipeline where appropriate. Report the model returned by the endpoint rather than assuming a provider. Match every asset to a coherent art direction: consistent palette, style, and resolution across sprites, backgrounds, and UI textures.",
  },
  {
    id: "research-report",
    name: "Deep Research Report",
    description:
      'Structured multi-source research: outline, evidence-gathering, citations, and a balanced report. User scenario: "Write me a research report on AI in healthcare" or "What does the data say about electric vehicle adoption?"',
    triggers: [
      "research report",
      "research on",
      "study",
      "analysis of",
      "white paper",
      "literature review",
      "compare and contrast",
      "market research",
      "deep dive",
      "survey of",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["explanation", "general", "writing"],
    requiresTools: [],
    instructions:
      "Build a research outline first (items + fields), then gather evidence from multiple sources, tracking every claim back to a citation. Synthesize a balanced report with an executive summary, findings by section, and a sources list. Cite only source URLs provided in the live evidence, copying each URL exactly; omit any remembered source that was not fetched. Never fabricate or repair a URL from memory. Mark uncertainty explicitly, state confidence per claim, and date-stamp time-sensitive data.",
  },
  {
    id: "document-generation",
    name: "Document & PDF Generation",
    description:
      'Contracts, invoices, letters, and formatted documents. User scenario: "Create a PDF invoice for my freelance work" or "Draft a service contract for my client."',
    triggers: [
      "invoice",
      "contract",
      "letter",
      "report",
      "memo",
      "business letter",
      "formal document",
      "pdf",
      "docx",
      "word document",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["writing", "general", "explanation"],
    requiresTools: [],
    instructions:
      "Identify the document type and audience first, then produce clean professional output in the requested format (structured text, printable HTML, or PDF). Use exactly the sections the user asks for; never invent personal facts, legal specifics, or figures. Keep formatting consistent and proofread the final text.",
  },
  {
    id: "data-analysis",
    name: "Data Analysis & Spreadsheets",
    description:
      'Dataset analysis, statistics, summaries, and spreadsheet structures. User scenario: "Analyze this sales CSV and tell me the trends" or "Build me a budget tracker spreadsheet."',
    triggers: [
      "analyze data",
      "dataset",
      "csv",
      "spreadsheet",
      "excel",
      "statistics",
      "data analysis",
      "dashboard data",
      "sales data",
      "metrics",
      "trends",
      "charts",
      "budget",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "explanation", "writing"],
    requiresTools: [],
    instructions:
      "Identify the key variables and the question being asked first, then compute and state the relevant total, average, trend, and outliers. Present findings with clear tables or charts, show the reasoning behind each conclusion, and cross-check every percentage, formula, and forecast against the source values before answering. Flag data-quality issues such as missing values, inconsistencies, and small sample sizes. Never invent data points that are not in the dataset.",
  },
  {
    id: "marketing-copywriting",
    name: "Marketing & Brand Copywriting",
    description:
      'Brand voice, campaigns, ad copy, landing pages, SEO content, and social posts. User scenario: "Write launch copy for my new coffee brand" or "Create a 30-day social media content plan."',
    triggers: [
      "marketing",
      "ad copy",
      "campaign",
      "brand",
      "tagline",
      "slogan",
      "landing page copy",
      "seo",
      "blog post",
      "social media",
      "newsletter",
      "email campaign",
      "content plan",
      "pitch deck copy",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["writing", "general", "explanation"],
    requiresTools: [],
    instructions:
      'Establish the brand voice and target audience first, then write persuasive, specific copy with a clear call to action. Offer multiple headline options, keep SEO keywords natural, and structure longer pieces (campaigns, calendars, email sequences) in scannable sections. Never present invented business facts as real: discounts, shipping policies, awards, customer counts, founder stories, facilities, roast schedules, fulfillment speed, and sourcing claims must come from the user. If the user supplied no business facts, do not invent an origin story or operating process. When a missing fact would improve the copy, bracket the entire claim as an explicit option, e.g. "[Optional launch offer: 15% off first order]" or "[Insert verified sourcing claim]"; do not blend an unsupported claim into otherwise publishable body copy. No filler — every line must earn its place.',
  },
  {
    id: "translation-localization",
    name: "Translation & Localization",
    description:
      'Accurate translation with cultural adaptation, tone preservation, and terminology consistency. User scenario: "Translate my landing page into Spanish" or "Localize this app for the Japanese market."',
    triggers: [
      "translate",
      "translation",
      "localize",
      "localization",
      "in french",
      "in spanish",
      "in tagalog",
      "in japanese",
      "in german",
      "into english",
      "multilingual",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["writing", "general", "explanation"],
    requiresTools: [],
    instructions:
      "Translate meaning, tone, and cultural nuance — not just words. Preserve formatting, technical terms, and proper nouns; adapt idioms and cultural references for the target audience. Provide the translated text first, then a brief note on adaptation choices and terminology consistency across the piece.",
  },
  {
    id: "live-data-utilities",
    name: "Live Data & Utility Lookups",
    description:
      'Weather, time zones, currency conversion, unit conversion, calculations, and quick factual lookups. User scenario: "Convert 5000 PHP to USD" or "What is the weather in Tokyo right now?"',
    triggers: [
      "convert",
      "currency",
      "exchange rate",
      "weather",
      "forecast",
      "temperature",
      "time zone",
      "what time",
      "unit conversion",
      "how many",
      "calculate",
      "calculator",
      "weight",
      "distance",
    ],
    phase: "IMPLEMENTING",
    priority: 18,
    dependencies: [],
    compatibleIntents: ["general", "explanation"],
    requiresTools: [],
    instructions:
      "For live data (weather, currency, time zones), give the current value with the source and timestamp, and note when rates or conditions change frequently. NEVER give current values from memory: if live evidence is unavailable, say clearly that live data could not be retrieved instead of approximating. For calculations and conversions, show the steps briefly, round sensibly, and state assumptions such as the rate, date, and locale explicitly.",
  },
  {
    id: "education-tutor",
    name: "Education & Learning Tutor",
    description:
      'Step-by-step teaching, learning paths, practice exercises, and plain-language explanations. User scenario: "Teach me JavaScript from zero" or "Explain quantum computing like I am 12."',
    triggers: [
      "teach me",
      "learn",
      "tutorial",
      "explain like",
      "beginner",
      "from zero",
      "study plan",
      "practice",
      "lesson",
      "homework",
      "exam prep",
      "course",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["explanation", "general", "writing"],
    requiresTools: [],
    instructions:
      "Diagnose the learner level first, then teach in small concrete steps with examples and short practice exercises. Use plain-language analogies, define every technical term before using it, and end with a checkpoint question or next-step exercise to confirm understanding.",
  },
  {
    id: "accessibility-compliance",
    name: "Accessibility Compliance",
    description:
      'WCAG 2.2 AA audits and accessible markup, color contrast, keyboard navigation, and ARIA guidance. User scenario: "Make my landing page WCAG compliant" or "Is my website accessible for screen readers?"',
    triggers: [
      "accessible",
      "accessibility",
      "wcag",
      "screen reader",
      "aria",
      "contrast",
      "keyboard navigation",
      "a11y",
    ],
    phase: "IMPLEMENTING",
    priority: 22,
    dependencies: [],
    compatibleIntents: ["app", "code-help", "explanation", "general"],
    requiresTools: [],
    instructions:
      "Audit against WCAG 2.2 AA: semantic structure, focus management, color contrast, form labels, and ARIA. Rank issues by severity and give concrete fixes with code whenever markup is shared. Verify keyboard-only navigation and screen-reader announcements in the fixes you suggest.",
  },
  {
    id: "business-planning",
    name: "Business Planning & Startup Strategy",
    description:
      'Business plans, go-to-market strategy, pricing, financial projections, and pitch decks. User scenario: "Help me plan a startup — pricing and go-to-market" or "Write my business plan."',
    triggers: [
      "business plan",
      "startup",
      "go-to-market",
      "pricing strategy",
      "financial projection",
      "pitch deck",
      "business model",
      "revenue model",
      "mvp strategy",
      "market entry",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "writing", "explanation"],
    requiresTools: [],
    instructions:
      "Structure answers around problem, solution, market, business model, and execution. Make assumptions explicit, label every example figure as an assumption or illustrative estimate, give ranges for financial figures, and clearly separate facts from estimates. Always end with prioritized next actions the user can take within the week.",
  },
  {
    id: "resume-career",
    name: "Resume & Career Coaching",
    description:
      'ATS-friendly resumes, cover letters, LinkedIn profiles, and interview preparation. User scenario: "Rewrite my resume for a data science role" or "Prepare me for a frontend interview."',
    triggers: [
      "resume",
      "cv",
      "cover letter",
      "linkedin",
      "job application",
      "interview",
      "career",
      "portfolio",
      "hire me",
      "job posting",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["writing", "general"],
    requiresTools: [],
    instructions:
      "Ask for missing critical details (role, experience level, target industry) when needed, then rewrite with action verbs, quantified achievements, and role-matched keywords. Keep the user's real facts — never invent experience, employers, titles, or credentials. Tailor each section to the specific role they are applying for.",
  },
  {
    id: "creative-writing",
    name: "Creative Writing",
    description:
      'Stories, poems, scripts, dialogue, and creative prose in any genre or tone. User scenario: "Write me a short story about a lighthouse keeper" or "Help me write a poem for my wedding."',
    triggers: [
      "story",
      "poem",
      "novel",
      "fiction",
      "script",
      "dialogue",
      "creative writing",
      "lyrics",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["writing", "general", "explanation"],
    requiresTools: [],
    instructions:
      "Match the requested form (story, poem, script, dialogue) and tone, then write with concrete sensory detail and natural rhythm. Establish voice, setting, and stakes quickly; show, don't tell. Offer a short revision note or alternate ending when useful.",
  },
  {
    id: "presentation-design",
    name: "Presentation & Slide Deck Design",
    description:
      'Deck outlines, slide-by-slide structures, speaker notes, and narrative arcs. User scenario: "Outline a 10-slide pitch for my startup" or "Help me structure my keynote presentation."',
    triggers: [
      "presentation",
      "slide deck",
      "powerpoint",
      "google slides",
      "speaker notes",
      "slideshow",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["writing", "general", "explanation"],
    requiresTools: [],
    instructions:
      'Design the deck\'s narrative arc first — hook, structure, call to action — then produce a slide-by-slide outline with a title, key points, and speaker notes per slide. Keep one idea per slide, favor short phrases over paragraphs, and suggest a visual for every complex data point. Never invent statistics: use placeholders like "[Insert verified statistic]" unless the user supplied the number.',
  },
  {
    id: "personal-productivity",
    name: "Personal Productivity & Planning",
    description:
      'Daily planning, task prioritization, time management, and habit systems. User scenario: "Plan my day" or "Help me build a habit tracking system."',
    triggers: [
      "plan my day",
      "task list",
      "to-do",
      "prioritize",
      "time management",
      "habit tracker",
      "get organized",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "writing", "explanation"],
    requiresTools: [],
    instructions:
      'Turn goals into a concrete, prioritized action plan with time-boxed tasks. Never assume times the user did not give: use placeholders like "[Team meeting — actual time]" or label every assumed time as an assumption. Use simple frameworks such as MITs, the Eisenhower matrix, or time blocking, and adapt to the user\'s energy patterns. End with a lightweight tracking method the user will actually maintain.',
  },
  {
    id: "personal-finance",
    name: "Personal Finance & Budgeting",
    description:
      'Budgets, savings plans, debt payoff strategies, and investing basics. User scenario: "Build a monthly budget for my family" or "How do I start an emergency fund?"',
    triggers: [
      "budget",
      "savings plan",
      "debt payoff",
      "investing basics",
      "emergency fund",
      "financial plan",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "explanation", "writing"],
    requiresTools: [],
    instructions:
      "Start from the user's income, expenses, and goals, then build a realistic budget or plan with specific numbers. Separate needs from wants, show the math behind every recommendation, and verify that every itemized budget adds exactly to the stated total and percentage. Flag risks. Give ranges and clear disclaimers for investment advice — never guarantee returns.",
  },
  {
    id: "travel-planning",
    name: "Travel & Trip Planning",
    description:
      'Itineraries, trip logistics, packing lists, and destination guidance. User scenario: "Plan a 5-day Tokyo itinerary" or "What should I pack for a beach vacation?"',
    triggers: [
      "itinerary",
      "travel plan",
      "vacation plan",
      "packing list",
      "road trip",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "explanation", "writing"],
    requiresTools: [],
    instructions:
      "Plan around the traveler's dates, budget, and interests: recommend a realistic itinerary with travel times, must-see stops, and backup options. Make sure every activity physically fits: start time + duration + travel buffer must not overlap the next activity. Allow at least 30 minutes for any ride, drive, walk, or venue transfer unless the locations are explicitly adjacent, and mark unknown details as assumptions. Include practical details such as transit, booking tips, and local customs, plus a packing checklist.",
  },
  {
    id: "fitness-nutrition",
    name: "Fitness & Nutrition Planning",
    description:
      'Workout plans, meal planning, calorie targets, and training programs. User scenario: "Build me a home workout plan" or "Plan a week of high-protein meals."',
    triggers: [
      "workout plan",
      "exercise routine",
      "training program",
      "meal plan",
      "diet plan",
      "nutrition",
      "fitness goal",
      "weight loss plan",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "explanation", "writing"],
    requiresTools: [],
    instructions:
      "Design a plan matched to the user's goal (strength, endurance, weight), current level, equipment, and schedule. Give specific exercises with sets and reps, and meals with portions, plus progression and rest guidance. Recommend stable surfaces only (never chairs or unstable furniture), include progression for beginners, and add safety notes — recommend consulting a professional for medical conditions.",
  },
  {
    id: "event-planning",
    name: "Event Planning",
    description:
      'Event checklists, party planning, wedding planning, and timelines with deadlines. User scenario: "Plan a birthday party for 20 people" or "Give me a wedding planning checklist."',
    triggers: [
      "event planning",
      "party planning",
      "wedding planning",
      "event checklist",
      "celebration plan",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "writing", "explanation"],
    requiresTools: [],
    instructions:
      "Build a complete event plan: date, venue, guest list, budget, timeline, vendors, and a checklist with deadlines. Work backward from the event date and surface the critical-path items first. Provide contingency plans for weather, cancellations, and vendor issues.",
  },
  {
    id: "study-aids",
    name: "Study Aids & Practice Materials",
    description:
      'Quizzes, flashcards, study guides, and practice tests on any topic. User scenario: "Make me a quiz on World War II" or "Create flashcards for Spanish vocabulary."',
    triggers: [
      "quiz",
      "flashcards",
      "study guide",
      "practice test",
      "revision notes",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["general", "explanation", "writing"],
    requiresTools: [],
    instructions:
      "Create study materials from the topic: key concepts, concise summaries, practice questions with an answer key, and flashcards. Match the difficulty to the learner's level and include spaced-repetition or self-testing guidance. Explain the reasoning behind every answer.",
  },
  {
    id: "meeting-notes",
    name: "Meeting Notes & Summaries",
    description:
      'Meeting summaries, action items, minutes, and decision recaps. User scenario: "Summarize these meeting notes" or "Extract action items from this conversation."',
    triggers: [
      "meeting notes",
      "meeting summary",
      "meeting minutes",
      "action items",
      "meeting recap",
    ],
    phase: "IMPLEMENTING",
    priority: 20,
    dependencies: [],
    compatibleIntents: ["writing", "general", "explanation"],
    requiresTools: [],
    instructions:
      'Extract decisions, discussion points, and owners with deadlines into clear structured notes. Only list actions, owners, and deadlines that actually appear in the source material — never infer them. A scheduled meeting with no explicitly named owner belongs in the summary or schedule, not the action-item table; never assign it to "Team". Put anything extra under a clearly labelled "Suggested Follow-ups" section, separate from confirmed actions. End with an action-item list (owner, task, due date) and ask for clarification when details are ambiguous.',
  },
  {
    id: "user-learning",
    name: "User Learning & Memory",
    description:
      'Durable user memory: remember, recall, and forget preferences and facts. User scenario: "Remember I prefer dark mode" or "What do you know about me?"',
    triggers: [
      "remember",
      "learn about me",
      "my preference",
      "what do you know about me",
      "forget",
    ],
    phase: "IMPLEMENTING",
    priority: 18,
    dependencies: [],
    compatibleIntents: ["general", "writing", "explanation"],
    requiresTools: [],
    instructions:
      "Learn durable user facts only with explicit consent via the userLearningService (R2 /api/memory endpoints) using an unguessable userId — never default_user. Separate durable preferences from temporary task details, refuse secrets and sensitive PII, confirm success only after a 2xx store/delete response, apply saved facts quietly when relevant, and support recall ('what do you know about me') and forget without inventing facts.",
  },
];
